version: '3.9'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
      - ./mssql/:/usr/src/app/
    command: ["sh", "-c", "chmod +x /usr/src/app/entrypoint.sh && chmod +x /usr/src/app/import-data.sh && /usr/src/app/entrypoint.sh"]
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=ifpb
      - POSTGRES_DB=idados
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_PASSWORD=An0thrS3crt
      - MYSQL_USER=ifpb
      - MYSQL_DATABASE=idados
  minio:
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    image: minio/minio:RELEASE.2021-12-20T22-07-16Z.fips
    environment:
      MINIO_ROOT_USER: FFD34B2AC56E76E8BB9E7EFD7D283
      MINIO_ROOT_PASSWORD: 47A13EFAB1CA1F253FD6F56DEF769
    volumes:
      - ~/apps/minio:/data
